echo ">>> ====================================="
echo ">>> SFUMATO WATCH (RELEASE MODE)"
echo ">>> ====================================="
echo ""
echo "Building and watching for changes..."
sass --style=compressed --no-source-map --watch "styleguide/scss/sfumato.scss" "styleguide/stylesheets/sfumato.css"
