echo ">>> ====================================="
echo ">>> SFUMATO WATCH (DEV MODE)"
echo ">>> ====================================="
echo ""
echo "Building and watching for changes..."
sass --style=expanded --embed-sources --watch "styleguide/scss/sfumato.scss" "styleguide/stylesheets/sfumato.css"
